
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "gameunit.sol";
// This is class that describes you smart contract.
contract warrior is gameunit{
    
    constructor(uint _powerofattack, uint _defense, uint _health) public {
        
        tvm.accept();
        powerofattack =_powerofattack;
        defense=_defense;
        health=_health;
    }

    function mygetpowerofattackw() public view returns (uint) {
        tvm.accept();
        return powerofattack;
    }
    function mygetdefensew() public view returns (uint) {
        tvm.accept();
        return defense;
    }
    // function mygethealthw() public view returns (uint) {
    //     tvm.accept();
    //     return health;
    // }
}
